import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Selector} from "@/app/components/selector";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="coffee">
      <body className="bg-neutral">
      <div className="flex flex-col items-center">
        <div className="max-w-screen-md min-h-[100vh] w-full flex flex-col">

          <Selector/>

          {children}

        </div>
      </div>
      </body>
      </html>
  )
}
